spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog.yaml

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true